n1 = int(input("Digite um número para ver sua tabuada: "))
print("-----------------------------------------------")
a = n1 *1
b = n1 *2
c = n1 *3
d = n1 *4
e = n1 *5
f = n1 *6
g = n1 *7
h = n1 *8
i = n1 *9
j = n1 *10
print(f"{n1} X 1 = {a}")
print(f"{n1} X 2 = {b}")
print(f"{n1} X 3 = {c}")
print(f"{n1} X 4 = {d}")
print(f"{n1} X 5 = {e}")
print(f"{n1} X 6 = {f}")
print(f"{n1} X 7 = {g}")
print(f"{n1} X 8 = {h}")
print(f"{n1} X 9 = {i}")
print(f"{n1} X 10 = {j}")